### ISSUE TITLE
新问题

### ISSUE THREAD

**Issue by Gaoyifei1011** [Melon-Studio/DarkMode2#1]
看见您将原来的仓库变成了只读模式，并创建了新的仓库，这个是Dark Mode 2.0版本吗？
那个Auto Dark Mode软件现在已经修复了22621不能正常修复深浅色模式的问题，那未来Dark Mode软件会跟进吗？
未来有机会发布一个Msix安装包并上架到商店吗？

**Comment by 6get-xiaofan** [comment]
是，会，有
