### ISSUE TITLE
请问如何完全卸载并清除残留文件

### ISSUE THREAD

**Issue by domoxiaojun** [Melon-Studio/DarkMode2#16]
删除注册表后,任务栏图标和通知项目里依旧存在

**Comment by 6get-xiaofan** [comment]
删除注册表后，直接删除软件文件夹即可，如果之前设置了开机自启，你需要在软件中关闭开机自启，如果已经删除，你需要到任务计划程序中删除开机自启的任务计划，如果使用过旧版本的程序，程序会在注册表中创建开机自启的项，你可以使用杀毒软件清理加速功能删除开机自启的无效注册项。
