### ISSUE TITLE
关于系统光标

### ISSUE THREAD

**Issue by gwy641815467** [Melon-Studio/DarkMode2#21]
自定义-系统光标 能不能给一个切换开关？因为我自己自定义了鼠标指针，这样会导致每次切换主题之后都把我的鼠标指针修改成默认的了，所以我想这个功能可以加一个开关

**Comment by bao-cn** [comment]
此功能已提上日程，预计下个版本增加

**Comment by bao-cn** [comment]
新版本已修复，请下载2.1.2版本
