### ISSUE TITLE
单击任务栏无法最小化

### ISSUE THREAD

**Issue by AnnualfireCHW** [Melon-Studio/DarkMode2#36]
如题单击任务栏时应无法最小化，需要点击窗口栏。

**Comment by bao-cn** [comment]
由于使用第三方开发的UI库，此类和UI逻辑相关的问题将不会去修复，感谢反馈，UI库有新版本时软件会自动支持到最新版本，UI问题可以去WPF-UI的库中反馈。

**Comment by AnnualfireCHW** [comment]
> 由于使用第三方开发的UI库，此类和UI逻辑相关的问题将不会去修复，感谢反馈，UI库有新版本时软件会自动支持到最新版本，UI问题可以去WPF-UI的库中反馈。

原来如此。请给出你所说的反馈链接。否则真的很影响用户体验。

**Comment by bao-cn** [comment]
> > 由于使用第三方开发的UI库，此类和UI逻辑相关的问题将不会去修复，感谢反馈，UI库有新版本时软件会自动支持到最新版本，UI问题可以去WPF-UI的库中反馈。
> 
> 原来如此。请给出你所说的反馈链接。否则真的很影响用户体验。

https://github.com/lepoco/wpfui
