### ISSUE TITLE
AMD显卡驱动问题导致鼠标白色会消失，但在切换深色浅色时，系统会重置鼠标为白色

### ISSUE THREAD

**Issue by holydoooge** [Melon-Studio/DarkMode2#42]
非软件bug，AMD显卡驱动问题导致鼠标会变成白色或者透明非常影响显示，将鼠标调成黑色就不会影响显示了，但是在切换深色和浅色模式的时候windows会重置鼠标颜色为白色，希望能出一个固定鼠标颜色的默认
<img width="744" alt="Snipaste_2023-10-21_09-29-19" src="https://github.com/Melon-Studio/DarkMode2/assets/83122420/0f74d6fa-8260-44cb-aaaf-013b580b7da5">

**Comment by bao-cn** [comment]
其实支持此功能，只要浅色和深色设置为同一种即可
![image](https://github.com/Melon-Studio/DarkMode2/assets/57002549/aa19bc32-c096-488b-9286-9708c554056a)
