### ISSUE TITLE
软件不能自启动

### ISSUE THREAD

**Issue by cong11233** [Melon-Studio/DarkMode2#44]
DarkMode版本2.0.9
电脑系统
版本	Windows 11 专业版
版本	22H2
安装日期	‎2023/‎7/‎19
操作系统版本	22621.2283
系统类型	64 位操作系统, 基于 x64 的处理器

**Comment by bao-cn** [comment]
最新版本的启动注册表设置在了32位的启动目录中，下个版本将得到修复
