### ISSUE TITLE
我的DarkMode2 Beta使用体验总结

### ISSUE THREAD

**Issue by doudou5776** [Melon-Studio/DarkMode2#8]
尊敬的DarkMode2开发者你们好,很荣幸能够参与DarkMode2的测试,首先感谢你们为我们开发出了这样一款开源的自动切换Windows系统界面深色、浅色模式的程序。经过了这几天的使用，我发现在目前版本中还有一些不太完善的地方。接下来我将会把问题一一列举出来，具体问题如下：
1.	在当前版本中为用户提供了两种自定义选项，一种是通过用户手动设置日出日落时间来进行深色和浅色模式之间的互换，另一种是通过使用Windows位置服务来获取并判断用户设备目前所处的地区日出日落时间，从而实现深色和浅色模式的自动切换。但是目前该功能好像还不太稳定，我已经授权Dark Mode2通过使用Windows位置服务来获取我的设备位置并自动判断日出日落时间以便切换深色和浅色模式。但是到了日落时间以后我打开电脑发现既没有切换成功，也没有显示我当前所在的位置的经纬度等参数。
![图片1](https://user-images.githubusercontent.com/116343539/197149542-41e278ef-aab9-4909-a9e3-9cfaa886cb61.jpg)
2.虽然目前在我的设备上并没有出现兼容性或是稳定性问题，但是我希望你们能够持续优化应用的稳定性和兼容性。
以上就是我的反馈，你们可以根据需要按需采纳，希望能够通过我们的共同努力使DarkMode2变得更好。

**Comment by 6get-xiaofan** [comment]
Beta version is the function development phase of the program. At present, there is no Sunrise Sunset Mode added, but a front-end effect has been made. The function is expected to be developed in the future.

*Issues will not be closed, issue number appended when development is complete.

**Comment by doudou5776** [comment]
当前版本中应用程序的自动更新功能暂时无法使用，希望在后续版本中能够将该功能调整为可用状态。
![屏幕截图 2022-10-21 163724](https://user-images.githubusercontent.com/116343539/197152464-ae8b5e4a-d06b-4aa0-a072-8764edea5566.jpg)

**Comment by 6get-xiaofan** [comment]
> 当前版本中应用程序的自动更新功能暂时无法使用，希望在后续版本中能够将该功能调整为可用状态。 ![屏幕截图 2022-10-21 163724](https://user-images.githubusercontent.com/116343539/197152464-ae8b5e4a-d06b-4aa0-a072-8764edea5566.jpg)

This function is planned to be enabled in the Release version, but not in the Beta version.

**Comment by doudou5776** [comment]
> Beta version is the function development phase of the program. At present, there is no Sunrise Sunset Mode added, but a front-end effect has been made. The function is expected to be developed in the future.
> 
> *Issues will not be closed, issue number appended when development is complete.

好的

**Comment by doudou5776** [comment]
> > 当前版本中应用程序的自动更新功能暂时无法使用，希望在后续版本中能够将该功能调整为可用状态。 ![屏幕截图 2022-10-21 163724](https://user-images.githubusercontent.com/116343539/197152464-ae8b5e4a-d06b-4aa0-a072-8764edea5566.jpg)
> 
> This function is planned to be enabled in the Release version, but not in the Beta version.

好的，了解了。我还想问一下开发者，在正式版发布以后是否有将该应用上架至Microsoft Store的计划呢？

**Comment by 6get-xiaofan** [comment]
> 

According to the results of the last multi community vote, there are plans.

**Comment by doudou5776** [comment]
有关这个问题的讨论就到这里吧，我就关闭评论区了。

**Comment by doudou5776** [comment]
有有关这个问题的讨论就到这里结束吧，稍后我会把这个问题设置为已完成。
